version: '3.3'
services:
  postgres:
    image: postgres:12-alpine
    volumes:
    - data:/var/lib/postgresql/data
    environment:
    - POSTGRES_USER='postgres'
    - POSTGRES_PASSWORD='password'
    - POSTGRES_DB='type-one'
    ports:
    - '5432:5432'
volumes:
  data: